/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as AuthenticatedTutorRouteImport } from './routes/_authenticated/tutor'
import { Route as AuthenticatedClinicaRouteImport } from './routes/_authenticated/clinica'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedTutorIndexRouteImport } from './routes/_authenticated/tutor.index'
import { Route as AuthenticatedClinicaIndexRouteImport } from './routes/_authenticated/clinica.index'
import { Route as AuthenticatedTutorPetsRouteImport } from './routes/_authenticated/tutor.pets'
import { Route as AuthenticatedTutorAgendarRouteImport } from './routes/_authenticated/tutor.agendar'
import { Route as AuthenticatedClinicaVacinasRouteImport } from './routes/_authenticated/clinica.vacinas'
import { Route as AuthenticatedClinicaServicosRouteImport } from './routes/_authenticated/clinica.servicos'
import { Route as AuthenticatedClinicaProntuariosRouteImport } from './routes/_authenticated/clinica.prontuarios'
import { Route as AuthenticatedClinicaFinanceiroRouteImport } from './routes/_authenticated/clinica.financeiro'
import { Route as AuthenticatedClinicaEquipeRouteImport } from './routes/_authenticated/clinica.equipe'
import { Route as AuthenticatedClinicaCrmRouteImport } from './routes/_authenticated/clinica.crm'
import { Route as AuthenticatedClinicaConfiguracoesRouteImport } from './routes/_authenticated/clinica.configuracoes'
import { Route as AuthenticatedClinicaAlertasRouteImport } from './routes/_authenticated/clinica.alertas'
import { Route as AuthenticatedClinicaAgendaRouteImport } from './routes/_authenticated/clinica.agenda'
import { Route as AuthenticatedTutorPetsNovoRouteImport } from './routes/_authenticated/tutor.pets.novo'
import { Route as AuthenticatedTutorPetsPetIdRouteImport } from './routes/_authenticated/tutor.pets.$petId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTutorRoute = AuthenticatedTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClinicaRoute = AuthenticatedClinicaRouteImport.update({
  id: '/clinica',
  path: '/clinica',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTutorIndexRoute = AuthenticatedTutorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedTutorRoute,
} as any)
const AuthenticatedClinicaIndexRoute =
  AuthenticatedClinicaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClinicaRoute,
  } as any)
const AuthenticatedTutorPetsRoute = AuthenticatedTutorPetsRouteImport.update({
  id: '/pets',
  path: '/pets',
  getParentRoute: () => AuthenticatedTutorRoute,
} as any)
const AuthenticatedTutorAgendarRoute =
  AuthenticatedTutorAgendarRouteImport.update({
    id: '/agendar',
    path: '/agendar',
    getParentRoute: () => AuthenticatedTutorRoute,
  } as any)
const AuthenticatedClinicaVacinasRoute =
  AuthenticatedClinicaVacinasRouteImport.update({
    id: '/vacinas',
    path: '/vacinas',
    getParentRoute: () => AuthenticatedClinicaRoute,
  } as any)
const AuthenticatedClinicaServicosRoute =
  AuthenticatedClinicaServicosRouteImport.update({
    id: '/servicos',
    path: '/servicos',
    getParentRoute: () => AuthenticatedClinicaRoute,
  } as any)
const AuthenticatedClinicaProntuariosRoute =
  AuthenticatedClinicaProntuariosRouteImport.update({
    id: '/prontuarios',
    path: '/prontuarios',
    getParentRoute: () => AuthenticatedClinicaRoute,
  } as any)
const AuthenticatedClinicaFinanceiroRoute =
  AuthenticatedClinicaFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedClinicaRoute,
  } as any)
const AuthenticatedClinicaEquipeRoute =
  AuthenticatedClinicaEquipeRouteImport.update({
    id: '/equipe',
    path: '/equipe',
    getParentRoute: () => AuthenticatedClinicaRoute,
  } as any)
const AuthenticatedClinicaCrmRoute = AuthenticatedClinicaCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedClinicaRoute,
} as any)
const AuthenticatedClinicaConfiguracoesRoute =
  AuthenticatedClinicaConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedClinicaRoute,
  } as any)
const AuthenticatedClinicaAlertasRoute =
  AuthenticatedClinicaAlertasRouteImport.update({
    id: '/alertas',
    path: '/alertas',
    getParentRoute: () => AuthenticatedClinicaRoute,
  } as any)
const AuthenticatedClinicaAgendaRoute =
  AuthenticatedClinicaAgendaRouteImport.update({
    id: '/agenda',
    path: '/agenda',
    getParentRoute: () => AuthenticatedClinicaRoute,
  } as any)
const AuthenticatedTutorPetsNovoRoute =
  AuthenticatedTutorPetsNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedTutorPetsRoute,
  } as any)
const AuthenticatedTutorPetsPetIdRoute =
  AuthenticatedTutorPetsPetIdRouteImport.update({
    id: '/$petId',
    path: '/$petId',
    getParentRoute: () => AuthenticatedTutorPetsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/clinica': typeof AuthenticatedClinicaRouteWithChildren
  '/tutor': typeof AuthenticatedTutorRouteWithChildren
  '/p/$token': typeof PTokenRoute
  '/clinica/agenda': typeof AuthenticatedClinicaAgendaRoute
  '/clinica/alertas': typeof AuthenticatedClinicaAlertasRoute
  '/clinica/configuracoes': typeof AuthenticatedClinicaConfiguracoesRoute
  '/clinica/crm': typeof AuthenticatedClinicaCrmRoute
  '/clinica/equipe': typeof AuthenticatedClinicaEquipeRoute
  '/clinica/financeiro': typeof AuthenticatedClinicaFinanceiroRoute
  '/clinica/prontuarios': typeof AuthenticatedClinicaProntuariosRoute
  '/clinica/servicos': typeof AuthenticatedClinicaServicosRoute
  '/clinica/vacinas': typeof AuthenticatedClinicaVacinasRoute
  '/tutor/agendar': typeof AuthenticatedTutorAgendarRoute
  '/tutor/pets': typeof AuthenticatedTutorPetsRouteWithChildren
  '/clinica/': typeof AuthenticatedClinicaIndexRoute
  '/tutor/': typeof AuthenticatedTutorIndexRoute
  '/tutor/pets/$petId': typeof AuthenticatedTutorPetsPetIdRoute
  '/tutor/pets/novo': typeof AuthenticatedTutorPetsNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/p/$token': typeof PTokenRoute
  '/clinica/agenda': typeof AuthenticatedClinicaAgendaRoute
  '/clinica/alertas': typeof AuthenticatedClinicaAlertasRoute
  '/clinica/configuracoes': typeof AuthenticatedClinicaConfiguracoesRoute
  '/clinica/crm': typeof AuthenticatedClinicaCrmRoute
  '/clinica/equipe': typeof AuthenticatedClinicaEquipeRoute
  '/clinica/financeiro': typeof AuthenticatedClinicaFinanceiroRoute
  '/clinica/prontuarios': typeof AuthenticatedClinicaProntuariosRoute
  '/clinica/servicos': typeof AuthenticatedClinicaServicosRoute
  '/clinica/vacinas': typeof AuthenticatedClinicaVacinasRoute
  '/tutor/agendar': typeof AuthenticatedTutorAgendarRoute
  '/tutor/pets': typeof AuthenticatedTutorPetsRouteWithChildren
  '/clinica': typeof AuthenticatedClinicaIndexRoute
  '/tutor': typeof AuthenticatedTutorIndexRoute
  '/tutor/pets/$petId': typeof AuthenticatedTutorPetsPetIdRoute
  '/tutor/pets/novo': typeof AuthenticatedTutorPetsNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/clinica': typeof AuthenticatedClinicaRouteWithChildren
  '/_authenticated/tutor': typeof AuthenticatedTutorRouteWithChildren
  '/p/$token': typeof PTokenRoute
  '/_authenticated/clinica/agenda': typeof AuthenticatedClinicaAgendaRoute
  '/_authenticated/clinica/alertas': typeof AuthenticatedClinicaAlertasRoute
  '/_authenticated/clinica/configuracoes': typeof AuthenticatedClinicaConfiguracoesRoute
  '/_authenticated/clinica/crm': typeof AuthenticatedClinicaCrmRoute
  '/_authenticated/clinica/equipe': typeof AuthenticatedClinicaEquipeRoute
  '/_authenticated/clinica/financeiro': typeof AuthenticatedClinicaFinanceiroRoute
  '/_authenticated/clinica/prontuarios': typeof AuthenticatedClinicaProntuariosRoute
  '/_authenticated/clinica/servicos': typeof AuthenticatedClinicaServicosRoute
  '/_authenticated/clinica/vacinas': typeof AuthenticatedClinicaVacinasRoute
  '/_authenticated/tutor/agendar': typeof AuthenticatedTutorAgendarRoute
  '/_authenticated/tutor/pets': typeof AuthenticatedTutorPetsRouteWithChildren
  '/_authenticated/clinica/': typeof AuthenticatedClinicaIndexRoute
  '/_authenticated/tutor/': typeof AuthenticatedTutorIndexRoute
  '/_authenticated/tutor/pets/$petId': typeof AuthenticatedTutorPetsPetIdRoute
  '/_authenticated/tutor/pets/novo': typeof AuthenticatedTutorPetsNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/clinica'
    | '/tutor'
    | '/p/$token'
    | '/clinica/agenda'
    | '/clinica/alertas'
    | '/clinica/configuracoes'
    | '/clinica/crm'
    | '/clinica/equipe'
    | '/clinica/financeiro'
    | '/clinica/prontuarios'
    | '/clinica/servicos'
    | '/clinica/vacinas'
    | '/tutor/agendar'
    | '/tutor/pets'
    | '/clinica/'
    | '/tutor/'
    | '/tutor/pets/$petId'
    | '/tutor/pets/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/p/$token'
    | '/clinica/agenda'
    | '/clinica/alertas'
    | '/clinica/configuracoes'
    | '/clinica/crm'
    | '/clinica/equipe'
    | '/clinica/financeiro'
    | '/clinica/prontuarios'
    | '/clinica/servicos'
    | '/clinica/vacinas'
    | '/tutor/agendar'
    | '/tutor/pets'
    | '/clinica'
    | '/tutor'
    | '/tutor/pets/$petId'
    | '/tutor/pets/novo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/clinica'
    | '/_authenticated/tutor'
    | '/p/$token'
    | '/_authenticated/clinica/agenda'
    | '/_authenticated/clinica/alertas'
    | '/_authenticated/clinica/configuracoes'
    | '/_authenticated/clinica/crm'
    | '/_authenticated/clinica/equipe'
    | '/_authenticated/clinica/financeiro'
    | '/_authenticated/clinica/prontuarios'
    | '/_authenticated/clinica/servicos'
    | '/_authenticated/clinica/vacinas'
    | '/_authenticated/tutor/agendar'
    | '/_authenticated/tutor/pets'
    | '/_authenticated/clinica/'
    | '/_authenticated/tutor/'
    | '/_authenticated/tutor/pets/$petId'
    | '/_authenticated/tutor/pets/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PTokenRoute: typeof PTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tutor': {
      id: '/_authenticated/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof AuthenticatedTutorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clinica': {
      id: '/_authenticated/clinica'
      path: '/clinica'
      fullPath: '/clinica'
      preLoaderRoute: typeof AuthenticatedClinicaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tutor/': {
      id: '/_authenticated/tutor/'
      path: '/'
      fullPath: '/tutor/'
      preLoaderRoute: typeof AuthenticatedTutorIndexRouteImport
      parentRoute: typeof AuthenticatedTutorRoute
    }
    '/_authenticated/clinica/': {
      id: '/_authenticated/clinica/'
      path: '/'
      fullPath: '/clinica/'
      preLoaderRoute: typeof AuthenticatedClinicaIndexRouteImport
      parentRoute: typeof AuthenticatedClinicaRoute
    }
    '/_authenticated/tutor/pets': {
      id: '/_authenticated/tutor/pets'
      path: '/pets'
      fullPath: '/tutor/pets'
      preLoaderRoute: typeof AuthenticatedTutorPetsRouteImport
      parentRoute: typeof AuthenticatedTutorRoute
    }
    '/_authenticated/tutor/agendar': {
      id: '/_authenticated/tutor/agendar'
      path: '/agendar'
      fullPath: '/tutor/agendar'
      preLoaderRoute: typeof AuthenticatedTutorAgendarRouteImport
      parentRoute: typeof AuthenticatedTutorRoute
    }
    '/_authenticated/clinica/vacinas': {
      id: '/_authenticated/clinica/vacinas'
      path: '/vacinas'
      fullPath: '/clinica/vacinas'
      preLoaderRoute: typeof AuthenticatedClinicaVacinasRouteImport
      parentRoute: typeof AuthenticatedClinicaRoute
    }
    '/_authenticated/clinica/servicos': {
      id: '/_authenticated/clinica/servicos'
      path: '/servicos'
      fullPath: '/clinica/servicos'
      preLoaderRoute: typeof AuthenticatedClinicaServicosRouteImport
      parentRoute: typeof AuthenticatedClinicaRoute
    }
    '/_authenticated/clinica/prontuarios': {
      id: '/_authenticated/clinica/prontuarios'
      path: '/prontuarios'
      fullPath: '/clinica/prontuarios'
      preLoaderRoute: typeof AuthenticatedClinicaProntuariosRouteImport
      parentRoute: typeof AuthenticatedClinicaRoute
    }
    '/_authenticated/clinica/financeiro': {
      id: '/_authenticated/clinica/financeiro'
      path: '/financeiro'
      fullPath: '/clinica/financeiro'
      preLoaderRoute: typeof AuthenticatedClinicaFinanceiroRouteImport
      parentRoute: typeof AuthenticatedClinicaRoute
    }
    '/_authenticated/clinica/equipe': {
      id: '/_authenticated/clinica/equipe'
      path: '/equipe'
      fullPath: '/clinica/equipe'
      preLoaderRoute: typeof AuthenticatedClinicaEquipeRouteImport
      parentRoute: typeof AuthenticatedClinicaRoute
    }
    '/_authenticated/clinica/crm': {
      id: '/_authenticated/clinica/crm'
      path: '/crm'
      fullPath: '/clinica/crm'
      preLoaderRoute: typeof AuthenticatedClinicaCrmRouteImport
      parentRoute: typeof AuthenticatedClinicaRoute
    }
    '/_authenticated/clinica/configuracoes': {
      id: '/_authenticated/clinica/configuracoes'
      path: '/configuracoes'
      fullPath: '/clinica/configuracoes'
      preLoaderRoute: typeof AuthenticatedClinicaConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedClinicaRoute
    }
    '/_authenticated/clinica/alertas': {
      id: '/_authenticated/clinica/alertas'
      path: '/alertas'
      fullPath: '/clinica/alertas'
      preLoaderRoute: typeof AuthenticatedClinicaAlertasRouteImport
      parentRoute: typeof AuthenticatedClinicaRoute
    }
    '/_authenticated/clinica/agenda': {
      id: '/_authenticated/clinica/agenda'
      path: '/agenda'
      fullPath: '/clinica/agenda'
      preLoaderRoute: typeof AuthenticatedClinicaAgendaRouteImport
      parentRoute: typeof AuthenticatedClinicaRoute
    }
    '/_authenticated/tutor/pets/novo': {
      id: '/_authenticated/tutor/pets/novo'
      path: '/novo'
      fullPath: '/tutor/pets/novo'
      preLoaderRoute: typeof AuthenticatedTutorPetsNovoRouteImport
      parentRoute: typeof AuthenticatedTutorPetsRoute
    }
    '/_authenticated/tutor/pets/$petId': {
      id: '/_authenticated/tutor/pets/$petId'
      path: '/$petId'
      fullPath: '/tutor/pets/$petId'
      preLoaderRoute: typeof AuthenticatedTutorPetsPetIdRouteImport
      parentRoute: typeof AuthenticatedTutorPetsRoute
    }
  }
}

interface AuthenticatedClinicaRouteChildren {
  AuthenticatedClinicaAgendaRoute: typeof AuthenticatedClinicaAgendaRoute
  AuthenticatedClinicaAlertasRoute: typeof AuthenticatedClinicaAlertasRoute
  AuthenticatedClinicaConfiguracoesRoute: typeof AuthenticatedClinicaConfiguracoesRoute
  AuthenticatedClinicaCrmRoute: typeof AuthenticatedClinicaCrmRoute
  AuthenticatedClinicaEquipeRoute: typeof AuthenticatedClinicaEquipeRoute
  AuthenticatedClinicaFinanceiroRoute: typeof AuthenticatedClinicaFinanceiroRoute
  AuthenticatedClinicaProntuariosRoute: typeof AuthenticatedClinicaProntuariosRoute
  AuthenticatedClinicaServicosRoute: typeof AuthenticatedClinicaServicosRoute
  AuthenticatedClinicaVacinasRoute: typeof AuthenticatedClinicaVacinasRoute
  AuthenticatedClinicaIndexRoute: typeof AuthenticatedClinicaIndexRoute
}

const AuthenticatedClinicaRouteChildren: AuthenticatedClinicaRouteChildren = {
  AuthenticatedClinicaAgendaRoute: AuthenticatedClinicaAgendaRoute,
  AuthenticatedClinicaAlertasRoute: AuthenticatedClinicaAlertasRoute,
  AuthenticatedClinicaConfiguracoesRoute:
    AuthenticatedClinicaConfiguracoesRoute,
  AuthenticatedClinicaCrmRoute: AuthenticatedClinicaCrmRoute,
  AuthenticatedClinicaEquipeRoute: AuthenticatedClinicaEquipeRoute,
  AuthenticatedClinicaFinanceiroRoute: AuthenticatedClinicaFinanceiroRoute,
  AuthenticatedClinicaProntuariosRoute: AuthenticatedClinicaProntuariosRoute,
  AuthenticatedClinicaServicosRoute: AuthenticatedClinicaServicosRoute,
  AuthenticatedClinicaVacinasRoute: AuthenticatedClinicaVacinasRoute,
  AuthenticatedClinicaIndexRoute: AuthenticatedClinicaIndexRoute,
}

const AuthenticatedClinicaRouteWithChildren =
  AuthenticatedClinicaRoute._addFileChildren(AuthenticatedClinicaRouteChildren)

interface AuthenticatedTutorPetsRouteChildren {
  AuthenticatedTutorPetsPetIdRoute: typeof AuthenticatedTutorPetsPetIdRoute
  AuthenticatedTutorPetsNovoRoute: typeof AuthenticatedTutorPetsNovoRoute
}

const AuthenticatedTutorPetsRouteChildren: AuthenticatedTutorPetsRouteChildren =
  {
    AuthenticatedTutorPetsPetIdRoute: AuthenticatedTutorPetsPetIdRoute,
    AuthenticatedTutorPetsNovoRoute: AuthenticatedTutorPetsNovoRoute,
  }

const AuthenticatedTutorPetsRouteWithChildren =
  AuthenticatedTutorPetsRoute._addFileChildren(
    AuthenticatedTutorPetsRouteChildren,
  )

interface AuthenticatedTutorRouteChildren {
  AuthenticatedTutorAgendarRoute: typeof AuthenticatedTutorAgendarRoute
  AuthenticatedTutorPetsRoute: typeof AuthenticatedTutorPetsRouteWithChildren
  AuthenticatedTutorIndexRoute: typeof AuthenticatedTutorIndexRoute
}

const AuthenticatedTutorRouteChildren: AuthenticatedTutorRouteChildren = {
  AuthenticatedTutorAgendarRoute: AuthenticatedTutorAgendarRoute,
  AuthenticatedTutorPetsRoute: AuthenticatedTutorPetsRouteWithChildren,
  AuthenticatedTutorIndexRoute: AuthenticatedTutorIndexRoute,
}

const AuthenticatedTutorRouteWithChildren =
  AuthenticatedTutorRoute._addFileChildren(AuthenticatedTutorRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedClinicaRoute: typeof AuthenticatedClinicaRouteWithChildren
  AuthenticatedTutorRoute: typeof AuthenticatedTutorRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedClinicaRoute: AuthenticatedClinicaRouteWithChildren,
  AuthenticatedTutorRoute: AuthenticatedTutorRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PTokenRoute: PTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
